server:
  port: 6691

tenant: hippo

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hippo_manager?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8
    username: root
    password: root
    hikari:
      connectionTimeout: 60000
      idleTimeout: 60000
      validationTimeout: 3000
      maxLifetime: 60000
      loginTimeout: 5
      maximumPoolSize: 60
      minimumIdle: 10

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
